# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: preprocessor_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='preprocessor_service.proto',
  package='preprocessor_service',
  syntax='proto3',
  serialized_options=b'\252\002\032Clang.Preprocessor.Service',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1apreprocessor_service.proto\x12\x14preprocessor_service\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n\rResetResponse\x12\x0c\n\x04\x44one\x18\x01 \x01(\x08\"\x1e\n\x0eSetPathRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"1\n\x12PpSymbolDefinition\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\r\n\x05Value\x18\x02 \x01(\t\"?\n\x15PreprocessFileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x13\n\x0bresult_path\x18\x02 \x01(\t\"+\n\x16PreprocessFileResponse\x12\x11\n\tpp_result\x18\x01 \x01(\r\"\x92\x01\n\x15GetMacroNamesResponse\x12I\n\x07Symbols\x18\x01 \x03(\x0b\x32\x38.preprocessor_service.GetMacroNamesResponse.SymbolsEntry\x1a.\n\x0cSymbolsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"/\n\x19GetMacroExpansionsRequest\x12\x12\n\nmacro_name\x18\x01 \x01(\t\"V\n\rExpansionInfo\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x13\n\x0bline_number\x18\x03 \x01(\x03\x12\x11\n\targuments\x18\x04 \x03(\t\"U\n\x1aGetMacroExpansionsResponse\x12\x37\n\nexpansions\x18\x01 \x03(\x0b\x32#.preprocessor_service.ExpansionInfo2\x8a\x05\n\x0cPreprocessor\x12\x44\n\x05Reset\x12\x16.google.protobuf.Empty\x1a#.preprocessor_service.ResetResponse\x12N\n\x0eSetIncludePath\x12$.preprocessor_service.SetPathRequest\x1a\x16.google.protobuf.Empty\x12T\n\x14SetMacroProviderPath\x12$.preprocessor_service.SetPathRequest\x1a\x16.google.protobuf.Empty\x12R\n\x0e\x44\x65\x66inePpSymbol\x12(.preprocessor_service.PpSymbolDefinition\x1a\x16.google.protobuf.Empty\x12T\n\rGetMacroNames\x12\x16.google.protobuf.Empty\x1a+.preprocessor_service.GetMacroNamesResponse\x12k\n\x0ePreprocessFile\x12+.preprocessor_service.PreprocessFileRequest\x1a,.preprocessor_service.PreprocessFileResponse\x12w\n\x12GetMacroExpansions\x12/.preprocessor_service.GetMacroExpansionsRequest\x1a\x30.preprocessor_service.GetMacroExpansionsResponseB\x1d\xaa\x02\x1a\x43lang.Preprocessor.Serviceb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_RESETRESPONSE = _descriptor.Descriptor(
  name='ResetResponse',
  full_name='preprocessor_service.ResetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Done', full_name='preprocessor_service.ResetResponse.Done', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=110,
)


_SETPATHREQUEST = _descriptor.Descriptor(
  name='SetPathRequest',
  full_name='preprocessor_service.SetPathRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='preprocessor_service.SetPathRequest.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=142,
)


_PPSYMBOLDEFINITION = _descriptor.Descriptor(
  name='PpSymbolDefinition',
  full_name='preprocessor_service.PpSymbolDefinition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='preprocessor_service.PpSymbolDefinition.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Value', full_name='preprocessor_service.PpSymbolDefinition.Value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=193,
)


_PREPROCESSFILEREQUEST = _descriptor.Descriptor(
  name='PreprocessFileRequest',
  full_name='preprocessor_service.PreprocessFileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_name', full_name='preprocessor_service.PreprocessFileRequest.file_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result_path', full_name='preprocessor_service.PreprocessFileRequest.result_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=258,
)


_PREPROCESSFILERESPONSE = _descriptor.Descriptor(
  name='PreprocessFileResponse',
  full_name='preprocessor_service.PreprocessFileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pp_result', full_name='preprocessor_service.PreprocessFileResponse.pp_result', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=303,
)


_GETMACRONAMESRESPONSE_SYMBOLSENTRY = _descriptor.Descriptor(
  name='SymbolsEntry',
  full_name='preprocessor_service.GetMacroNamesResponse.SymbolsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='preprocessor_service.GetMacroNamesResponse.SymbolsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='preprocessor_service.GetMacroNamesResponse.SymbolsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=452,
)

_GETMACRONAMESRESPONSE = _descriptor.Descriptor(
  name='GetMacroNamesResponse',
  full_name='preprocessor_service.GetMacroNamesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Symbols', full_name='preprocessor_service.GetMacroNamesResponse.Symbols', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GETMACRONAMESRESPONSE_SYMBOLSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=452,
)


_GETMACROEXPANSIONSREQUEST = _descriptor.Descriptor(
  name='GetMacroExpansionsRequest',
  full_name='preprocessor_service.GetMacroExpansionsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='macro_name', full_name='preprocessor_service.GetMacroExpansionsRequest.macro_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=454,
  serialized_end=501,
)


_EXPANSIONINFO = _descriptor.Descriptor(
  name='ExpansionInfo',
  full_name='preprocessor_service.ExpansionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='preprocessor_service.ExpansionInfo.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_name', full_name='preprocessor_service.ExpansionInfo.file_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='line_number', full_name='preprocessor_service.ExpansionInfo.line_number', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arguments', full_name='preprocessor_service.ExpansionInfo.arguments', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=503,
  serialized_end=589,
)


_GETMACROEXPANSIONSRESPONSE = _descriptor.Descriptor(
  name='GetMacroExpansionsResponse',
  full_name='preprocessor_service.GetMacroExpansionsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='expansions', full_name='preprocessor_service.GetMacroExpansionsResponse.expansions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=591,
  serialized_end=676,
)

_GETMACRONAMESRESPONSE_SYMBOLSENTRY.containing_type = _GETMACRONAMESRESPONSE
_GETMACRONAMESRESPONSE.fields_by_name['Symbols'].message_type = _GETMACRONAMESRESPONSE_SYMBOLSENTRY
_GETMACROEXPANSIONSRESPONSE.fields_by_name['expansions'].message_type = _EXPANSIONINFO
DESCRIPTOR.message_types_by_name['ResetResponse'] = _RESETRESPONSE
DESCRIPTOR.message_types_by_name['SetPathRequest'] = _SETPATHREQUEST
DESCRIPTOR.message_types_by_name['PpSymbolDefinition'] = _PPSYMBOLDEFINITION
DESCRIPTOR.message_types_by_name['PreprocessFileRequest'] = _PREPROCESSFILEREQUEST
DESCRIPTOR.message_types_by_name['PreprocessFileResponse'] = _PREPROCESSFILERESPONSE
DESCRIPTOR.message_types_by_name['GetMacroNamesResponse'] = _GETMACRONAMESRESPONSE
DESCRIPTOR.message_types_by_name['GetMacroExpansionsRequest'] = _GETMACROEXPANSIONSREQUEST
DESCRIPTOR.message_types_by_name['ExpansionInfo'] = _EXPANSIONINFO
DESCRIPTOR.message_types_by_name['GetMacroExpansionsResponse'] = _GETMACROEXPANSIONSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResetResponse = _reflection.GeneratedProtocolMessageType('ResetResponse', (_message.Message,), {
  'DESCRIPTOR' : _RESETRESPONSE,
  '__module__' : 'preprocessor_service_pb2'
  # @@protoc_insertion_point(class_scope:preprocessor_service.ResetResponse)
  })
_sym_db.RegisterMessage(ResetResponse)

SetPathRequest = _reflection.GeneratedProtocolMessageType('SetPathRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETPATHREQUEST,
  '__module__' : 'preprocessor_service_pb2'
  # @@protoc_insertion_point(class_scope:preprocessor_service.SetPathRequest)
  })
_sym_db.RegisterMessage(SetPathRequest)

PpSymbolDefinition = _reflection.GeneratedProtocolMessageType('PpSymbolDefinition', (_message.Message,), {
  'DESCRIPTOR' : _PPSYMBOLDEFINITION,
  '__module__' : 'preprocessor_service_pb2'
  # @@protoc_insertion_point(class_scope:preprocessor_service.PpSymbolDefinition)
  })
_sym_db.RegisterMessage(PpSymbolDefinition)

PreprocessFileRequest = _reflection.GeneratedProtocolMessageType('PreprocessFileRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREPROCESSFILEREQUEST,
  '__module__' : 'preprocessor_service_pb2'
  # @@protoc_insertion_point(class_scope:preprocessor_service.PreprocessFileRequest)
  })
_sym_db.RegisterMessage(PreprocessFileRequest)

PreprocessFileResponse = _reflection.GeneratedProtocolMessageType('PreprocessFileResponse', (_message.Message,), {
  'DESCRIPTOR' : _PREPROCESSFILERESPONSE,
  '__module__' : 'preprocessor_service_pb2'
  # @@protoc_insertion_point(class_scope:preprocessor_service.PreprocessFileResponse)
  })
_sym_db.RegisterMessage(PreprocessFileResponse)

GetMacroNamesResponse = _reflection.GeneratedProtocolMessageType('GetMacroNamesResponse', (_message.Message,), {

  'SymbolsEntry' : _reflection.GeneratedProtocolMessageType('SymbolsEntry', (_message.Message,), {
    'DESCRIPTOR' : _GETMACRONAMESRESPONSE_SYMBOLSENTRY,
    '__module__' : 'preprocessor_service_pb2'
    # @@protoc_insertion_point(class_scope:preprocessor_service.GetMacroNamesResponse.SymbolsEntry)
    })
  ,
  'DESCRIPTOR' : _GETMACRONAMESRESPONSE,
  '__module__' : 'preprocessor_service_pb2'
  # @@protoc_insertion_point(class_scope:preprocessor_service.GetMacroNamesResponse)
  })
_sym_db.RegisterMessage(GetMacroNamesResponse)
_sym_db.RegisterMessage(GetMacroNamesResponse.SymbolsEntry)

GetMacroExpansionsRequest = _reflection.GeneratedProtocolMessageType('GetMacroExpansionsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETMACROEXPANSIONSREQUEST,
  '__module__' : 'preprocessor_service_pb2'
  # @@protoc_insertion_point(class_scope:preprocessor_service.GetMacroExpansionsRequest)
  })
_sym_db.RegisterMessage(GetMacroExpansionsRequest)

ExpansionInfo = _reflection.GeneratedProtocolMessageType('ExpansionInfo', (_message.Message,), {
  'DESCRIPTOR' : _EXPANSIONINFO,
  '__module__' : 'preprocessor_service_pb2'
  # @@protoc_insertion_point(class_scope:preprocessor_service.ExpansionInfo)
  })
_sym_db.RegisterMessage(ExpansionInfo)

GetMacroExpansionsResponse = _reflection.GeneratedProtocolMessageType('GetMacroExpansionsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETMACROEXPANSIONSRESPONSE,
  '__module__' : 'preprocessor_service_pb2'
  # @@protoc_insertion_point(class_scope:preprocessor_service.GetMacroExpansionsResponse)
  })
_sym_db.RegisterMessage(GetMacroExpansionsResponse)


DESCRIPTOR._options = None
_GETMACRONAMESRESPONSE_SYMBOLSENTRY._options = None

_PREPROCESSOR = _descriptor.ServiceDescriptor(
  name='Preprocessor',
  full_name='preprocessor_service.Preprocessor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=679,
  serialized_end=1329,
  methods=[
  _descriptor.MethodDescriptor(
    name='Reset',
    full_name='preprocessor_service.Preprocessor.Reset',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_RESETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetIncludePath',
    full_name='preprocessor_service.Preprocessor.SetIncludePath',
    index=1,
    containing_service=None,
    input_type=_SETPATHREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetMacroProviderPath',
    full_name='preprocessor_service.Preprocessor.SetMacroProviderPath',
    index=2,
    containing_service=None,
    input_type=_SETPATHREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DefinePpSymbol',
    full_name='preprocessor_service.Preprocessor.DefinePpSymbol',
    index=3,
    containing_service=None,
    input_type=_PPSYMBOLDEFINITION,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetMacroNames',
    full_name='preprocessor_service.Preprocessor.GetMacroNames',
    index=4,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_GETMACRONAMESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PreprocessFile',
    full_name='preprocessor_service.Preprocessor.PreprocessFile',
    index=5,
    containing_service=None,
    input_type=_PREPROCESSFILEREQUEST,
    output_type=_PREPROCESSFILERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetMacroExpansions',
    full_name='preprocessor_service.Preprocessor.GetMacroExpansions',
    index=6,
    containing_service=None,
    input_type=_GETMACROEXPANSIONSREQUEST,
    output_type=_GETMACROEXPANSIONSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PREPROCESSOR)

DESCRIPTOR.services_by_name['Preprocessor'] = _PREPROCESSOR

# @@protoc_insertion_point(module_scope)
